version: '3.8'

services:
  presence-api:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SHEET_RANGE=${GOOGLE_SHEET_RANGE}
      - CACHE_DURATION=${CACHE_DURATION}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 